### ISSUE TITLE
k8s charm should be able to use native LB for kube-api-lb to solve HA issue

### ISSUE THREAD

**Issue by CalvinHartwell** [juju-solutions/charm-aws-integrator#18]
Hi, 

This charm should be able to integrate with the native Kubernetes load-balancers to solve the kube-api-lb issue, OR should at least be able to obtain enough information to juju to reconfigure multiple load-balancers as VM in order to provide HA. 

I don't think it does this today, correct?

**Comment by tvansteenburgh** [comment]
Issue moved to https://bugs.launchpad.net/bugs/1809336.
