### ISSUE TITLE
k8s charm should be able to interact and set up AWS native docker registry and automatically integrate it with CDK

### ISSUE THREAD

**Issue by CalvinHartwell** [juju-solutions/charm-aws-integrator#19]
Hi all,

Low priority item, but nice to have feature. This charm should be able to configure and setup an AWS native docker registry and configure it to be used by CDK. It would be cool if it also pushed all of the CDK containers into it, so the customer does not need to rely on anything which is third-party. 

Cheers

**Comment by tvansteenburgh** [comment]
Issue moved to https://bugs.launchpad.net/bugs/1809337.
