### ISSUE TITLE
k8s charm should be able to interact with the native AWS directory service to configure an AD server

### ISSUE THREAD

**Issue by CalvinHartwell** [juju-solutions/charm-aws-integrator#20]
Hi all,

Another low-ticket item, but it would be cool if this charm could automatically configure an AD server using the native AD provided by AWS which can be used by Rancher or the cluster itself. 

Cheers

**Comment by tvansteenburgh** [comment]
Issue moved to https://bugs.launchpad.net/bugs/1809338.
