### ISSUE TITLE
aws integrator should also be able to configure and deploy the EFS provisioner for shared volumes 

### ISSUE THREAD

**Issue by CalvinHartwell** [juju-solutions/charm-aws-integrator#28]
Hi all,

We have seem some requirements for shared volumes which cannot be provided through EBS. These can be provided using EFS and the EFS provisioner workload, found here: [https://github.com/kubernetes-incubator/external-storage/tree/master/aws/efs](https://github.com/kubernetes-incubator/external-storage/tree/master/aws/efs)

Here are instructions for setting this up: [https://itnext.io/efs-persistent-volumes-on-aws-kubernetes-193e0035bbfb](https://itnext.io/efs-persistent-volumes-on-aws-kubernetes-193e0035bbfb)

Cheers

**Comment by tvansteenburgh** [comment]
Issue moved to https://bugs.launchpad.net/bugs/1809341.
